<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicommon\controllers;


class ActiveController extends \yii\rest\ActiveController
{
    /**
     * @inheritdoc
     * @var array
     */
    public $serializer = [
        '__class' => \yii\rest\Serializer::class,
        'collectionEnvelope' => 'items',
    ];

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->request->isPost || \Yii::$app->request->isPatch) {
            \Yii::$app->request->setHeader('Content-Type', 'application/json');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}