<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicommon\controllers;

use yii\filters\Cors;

/**
 * Class RestController
 * @package powerkernel\yiicommon\controllers
 */
class RestController extends \yii\rest\Controller
{

    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            '__class' => Cors::class,
        ];
        return $behaviors;
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->request->isPost || \Yii::$app->request->isPatch) {
            \Yii::$app->request->setHeader('Content-Type', 'application/json');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}