<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiicommon\controllers;

/**
 * Class RestController
 * @package powerkernel\yiicommon\controllers
 */
class RestController extends \yii\rest\Controller
{

    public $enableCsrfValidation = false;

    /**
     * @inheritdoc
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['corsFilter'] = [
            '__class' => \yii\filters\Cors::class,
        ];

        $behaviors['contentNegotiator'] = [
            '__class' => \yii\filters\ContentNegotiator::class,
            'formats' => [
                'application/json' => \yii\web\Response::FORMAT_JSON,
            ],
        ];

        return $behaviors;
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (\Yii::$app->request->isPost || \Yii::$app->request->isPatch) {
            \Yii::$app->request->setHeader('Content-Type', 'application/json');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}